# Generated by Django 4.0.2 on 2022-02-11 09:40

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='크루명')),
                ('description', models.TextField(verbose_name='한줄소개')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='크루 생성날짜')),
                ('meeting_type', models.CharField(choices=[('온라인', '온라인'), ('오프라인', '오프라인'), ('온/오프라인', '온/오프라인')], default='온/오프라인', max_length=6, verbose_name='모임형태')),
                ('meeting_time', models.CharField(max_length=20, verbose_name='모임시간')),
                ('community', models.CharField(choices=[('1청년부', '1청년부'), ('2청년부', '2청년부'), ('3청년부', '3청년부'), ('신혼브릿지', '신혼브릿지')], default='1청년부', max_length=6, verbose_name='크루 소속 공동체')),
                ('member_limit', models.PositiveSmallIntegerField(default=5, help_text='5~15명 이내로 설정해주세요', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(15)], verbose_name='최대 모임 인원')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
