# Generated by Django 4.0.2 on 2022-02-05 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='크루명')),
                ('description', models.TextField(verbose_name='한줄소개')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='크루 생성날짜')),
                ('meeting_type', models.CharField(choices=[('온라인', '온라인'), ('오프라인', '오프라인'), ('온/오프라인', '온/오프라인')], default='온/오프라인', max_length=6, verbose_name='모임형태')),
                ('meeting_time', models.CharField(max_length=20, verbose_name='모임시간')),
                ('community', models.CharField(choices=[('1청년부', '1청년부'), ('2청년부', '2청년부'), ('3청년부', '3청년부'), ('신혼브릿지', '신혼브릿지')], default='1청년부', max_length=6, verbose_name='크루 소속 공동체')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='크루매니저')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
