# Generated by Django 4.0.2 on 2022-03-28 10:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrewManager', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='한줄소개'),
        ),
    ]
