# Generated by Django 4.0.2 on 2022-02-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrewManager', '0002_crew_members_alter_crew_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='member_limit',
            field=models.PositiveSmallIntegerField(default=5, help_text='5~15명 이내로 설정해주세요', verbose_name='최대 모임 인원'),
        ),
    ]
