# Generated by Django 4.0.2 on 2022-02-07 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrewManager', '0003_crew_member_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='member_limit',
            field=models.PositiveSmallIntegerField(default=5, help_text='5~15명 이내로 설정해주세요', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(15)], verbose_name='최대 모임 인원'),
        ),
    ]
