# Generated by Django 4.0.2 on 2022-03-30 02:31

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CrewManager', '0004_alter_crew_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='crew/resize/%y%m%d', verbose_name='소개이미지'),
        ),
    ]
