# Generated by Django 4.0.2 on 2022-04-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrewManager', '0005_crew_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='abstract',
            field=models.CharField(default='', max_length=100, verbose_name='크루한줄설명'),
            preserve_default=False,
        ),
    ]
