# Generated by Django 4.0.2 on 2022-04-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrewManager', '0006_crew_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='meeting_limit',
            field=models.CharField(default='', max_length=30, verbose_name='모임제한'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crew',
            name='meeting_time',
            field=models.CharField(max_length=30, verbose_name='모임시간'),
        ),
    ]
