# Generated by Django 4.0.2 on 2022-04-05 13:30

import django.core.validators
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CrewManager', '0007_crew_meeting_limit_alter_crew_meeting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='crew/resize/%y%m%d', verbose_name='크루 소개 이미지 (정사각형)'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='meeting_limit',
            field=models.CharField(max_length=30, verbose_name='모임제한 (30자 이내)'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='meeting_time',
            field=models.CharField(max_length=30, verbose_name='모임시간 (30자 이내)'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='member_limit',
            field=models.PositiveSmallIntegerField(default=5, help_text='5~15명 이내로 설정해주세요', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(15)], verbose_name='최대 모임 인원 (본인 포함)'),
        ),
    ]
