# Generated by Django 4.0.2 on 2022-04-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrewManager', '0008_alter_crew_image_alter_crew_meeting_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='종료 시간'),
        ),
        migrations.AddField(
            model_name='crew',
            name='period',
            field=models.CharField(choices=[('매주', '매주'), ('격주', '격주'), ('선택안함', '선택안함')], default='선택안함', max_length=4, verbose_name='반복 주기'),
        ),
        migrations.AddField(
            model_name='crew',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='시작 시간'),
        ),
        migrations.AddField(
            model_name='crew',
            name='weekday',
            field=models.CharField(choices=[('월요일', '월요일'), ('화요일', '화요일'), ('수요일', '수요일'), ('목요일', '목요일'), ('금요일', '금요일'), ('토요일', '토요일'), ('일요일', '일요일'), ('선택안함', '선택안함')], default='선택안함', max_length=4, verbose_name='모임 요일'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='meeting_time',
            field=models.CharField(max_length=30, verbose_name='기타 모임시간'),
        ),
    ]
