# Generated by Django 4.0.2 on 2022-04-07 16:14

import ckeditor_uploader.fields
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CrewManager', '0012_alter_crew_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='community',
            field=models.IntegerField(choices=[(0, '1청년부'), (1, '2청년부'), (2, '3청년부'), (3, '신혼브릿지'), (4, '기타')], default=0, verbose_name='크루 소속 공동체 (크루리더가 소속된 공동체 = 예산사용공동체)'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='크루 설명 (모바일에 들어갈 사이즈입니다. 줄바꿈 확인필요, 이미지 업로드 가능)'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='모임 종료 시간 (21:00 와 같은 형식으로 적어주세요)'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='crew/resize/%y%m%d', verbose_name='크루 소개 이미지 (정사각형, 500x500이상)'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='meeting_limit',
            field=models.CharField(max_length=30, verbose_name='모임제한 (특별히 이런 사람들이 왔으면 좋겠다 같은 내용,30자 이내)'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='meeting_time',
            field=models.CharField(max_length=30, verbose_name='기타 모임시간 (나중에 시간을 정해야한다면 여기다 적어주세요)'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='name',
            field=models.CharField(max_length=30, verbose_name='크루명 (30자 이내)'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='period',
            field=models.CharField(choices=[('매주', '매주'), ('격주', '격주'), ('선택안함', '선택안함')], default='선택안함', max_length=4, verbose_name='모임 반복 주기'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='모임 시작 시간 (19:00 와 같은 형식으로 적어주세요)'),
        ),
    ]
