# Generated by Django 4.0.2 on 2022-04-11 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrewManager', '0013_alter_crew_community_alter_crew_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='kakao_room',
            field=models.URLField(blank=True, null=True, verbose_name='오픈카톡방 URL'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='member_limit',
            field=models.PositiveSmallIntegerField(default=5, help_text='5~15명 이내로 설정해주세요', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)], verbose_name='최대 모임 인원 (본인 포함)'),
        ),
    ]
