# Generated by Django 4.0.2 on 2022-02-05 17:06

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='이름')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', common.models.UserManager()),
            ],
        ),
    ]
