# Generated by Django 4.0.2 on 2022-03-27 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthyear',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='또래'),
        ),
        migrations.AddField(
            model_name='user',
            name='community',
            field=models.CharField(choices=[('1청년부', '1청년부'), ('2청년부', '2청년부'), ('3청년부', '3청년부'), ('신혼브릿지', '신혼브릿지'), ('기타', '기타')], default='1청년부', max_length=6, verbose_name='소속 공동체'),
        ),
    ]
