# Generated by Django 4.0.2 on 2022-03-28 08:43

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_birthyear_user_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='profile_image/%Y/%m'),
        ),
    ]
