# Generated by Django 4.0.2 on 2022-03-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.URLField(blank=True, null=True, verbose_name='프로파일이미지URL'),
        ),
    ]
