# Generated by Django 4.0.2 on 2022-03-27 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jsonform.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='계정 이름')),
                ('description', models.TextField(verbose_name='설명')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록날짜')),
                ('available', models.BooleanField(default=False, verbose_name='사용가능')),
                ('appkey', models.CharField(max_length=30, verbose_name='키')),
                ('secretkey', models.CharField(max_length=60, verbose_name='비밀 키')),
                ('useremail', models.EmailField(max_length=254, verbose_name='사용자 이메일')),
            ],
        ),
        migrations.CreateModel(
            name='ZoomMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetingid', models.IntegerField(default=0, verbose_name='id')),
                ('topic', models.CharField(max_length=60, verbose_name='모임 주제')),
                ('description', models.TextField(blank=True, null=True, verbose_name='모임 설명')),
                ('type_meeting', models.PositiveSmallIntegerField(choices=[(1, '일반'), (2, '예약'), (3, '반복'), (8, '반복예약')], default=1, verbose_name='모임 타입')),
                ('create_dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록날짜')),
                ('start_dt', models.DateTimeField(blank=True, null=True, verbose_name='시작시간')),
                ('duration', models.PositiveIntegerField(verbose_name='진행 시간')),
                ('password', models.CharField(default='', max_length=10, verbose_name='비밀번호')),
                ('join_url', models.URLField(default='', verbose_name='모임 URL')),
                ('settings', django_jsonform.models.fields.JSONField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account', to='zoom.zoomaccount', verbose_name='줌 계정')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
        ),
    ]
